# Render.com deployment configuration for La Vida Luca App
version: "1"

services:
  # Backend API Service
  - type: web
    name: lavidaluca-backend
    runtime: python3
    buildCommand: cd apps/backend && pip install -r requirements.txt
    startCommand: cd apps/backend && python -m gunicorn app_simple:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lavidaluca-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: CORS_ORIGINS
        value: '["https://lavidaluca-frontend.onrender.com","https://lavidaluca.fr","https://www.lavidaluca.fr"]'
      - key: LOG_LEVEL
        value: INFO

  # Frontend Next.js Service  
  - type: web
    name: lavidaluca-frontend
    runtime: node
    buildCommand: cd apps/web && npm ci && npm run build
    startCommand: cd apps/web && npm start
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: lavidaluca-backend
          property: host
      - key: NEXT_PUBLIC_APP_NAME
        value: "La Vida Luca"
      - key: NEXT_PUBLIC_APP_VERSION
        value: "1.0.0"
      - key: NEXT_PUBLIC_CONTACT_EMAIL
        value: "contact@lavidaluca.fr"
      - key: NEXT_PUBLIC_CONTACT_PHONE
        value: "+33123456789"
      - key: NEXT_PUBLIC_ENABLE_ANALYTICS
        value: "true"
      - key: NEXT_PUBLIC_DEBUG
        value: "false"

databases:
  - name: lavidaluca-db
    plan: starter
    region: oregon
    postgresMajorVersion: 15