services:
  - type: web
    name: lavidaluca-api
    env: python
    plan: free
    buildCommand: pip install -r apps/ia/requirements.txt
    startCommand: cd apps/ia && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lavidaluca-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

databases:
  - name: lavidaluca-db
    databaseName: lavidaluca
    user: lavidaluca_user
    plan: free