version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lavidaluca
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/lavidaluca
      SECRET_KEY: your-development-secret-key
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      ENVIRONMENT: development
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data: