# FastAPI backend deployment to Render
build:
  commands:
    - pip install -r requirements.txt

start:
  command: python startup.py && uvicorn main:app --host 0.0.0.0 --port $PORT

env:
  PYTHON_VERSION: 3.11.0