version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lavidaluca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/lavidaluca
      - SECRET_KEY=dev-secret-key-change-in-production
      - FIRST_SUPERUSER=admin@lavidaluca.com
      - FIRST_SUPERUSER_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: