services:
  - type: web
    name: lavidaluca-api
    env: python
    plan: standard
    buildCommand: cd apps/backend && pip install -r requirements.txt
    startCommand: cd apps/backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lavidaluca-db
          property: connectionString
      - key: SENTRY_DSN
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: lavidaluca-db
    plan: standard