name: Backend CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      working-directory: apps/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment variables
      working-directory: apps/backend
      run: |
        echo "SECRET_KEY=test-secret-key" >> .env
        echo "OPENAI_API_KEY=test-key" >> .env
        echo "ENVIRONMENT=testing" >> .env
    
    - name: Run tests
      working-directory: apps/backend
      run: |
        python -m pytest test_simple.py -v --tb=short
    
    - name: Run linting (optional)
      working-directory: apps/backend
      run: |
        pip install flake8
        flake8 app_simple.py --max-line-length=120 --extend-ignore=E203,W503
      continue-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}