name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy Backend to Render
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}" \
          -H "Content-Type: application/json" \
          -d '{
            "clearCache": false,
            "commitId": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}"
          }'
      
    - name: Verify backend deployment
      run: |
        echo "Backend deployment triggered successfully"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"

  deploy-frontend:
    name: Deploy Frontend to Render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy Frontend to Render
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}" \
          -H "Content-Type: application/json" \
          -d '{
            "clearCache": false,
            "commitId": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}"
          }'
        
    - name: Verify frontend deployment
      run: |
        echo "Frontend deployment triggered successfully"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"

  notify-deployment:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always() && github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment notification
      run: |
        if [[ "${{ needs.deploy-backend.result }}" == "success" && "${{ needs.deploy-frontend.result }}" == "success" ]]; then
          echo "✅ Deployment successful"
          echo "Backend: Deployed to Render"
          echo "Frontend: Deployed to Render"
        else
          echo "❌ Deployment failed"
          echo "Backend status: ${{ needs.deploy-backend.result }}"
          echo "Frontend status: ${{ needs.deploy-frontend.result }}"
          exit 1
        fi