name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Render
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_IA }}" \
          -H "Content-Type: application/json" \
          -d '{
            "clearCache": false,
            "commitId": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}"
          }'
      
    - name: Verify deployment
      run: |
        echo "Backend deployment triggered successfully"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"

  deploy-frontend:
    name: Deploy Frontend to Netlify
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'apps/web/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd apps/web
        npm ci
        
    - name: Build application
      run: |
        cd apps/web
        npm run build
        
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=apps/web/out --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
    - name: Verify deployment
      run: |
        echo "Frontend deployment completed successfully"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"

  notify-deployment:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always() && github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment notification
      run: |
        if [[ "${{ needs.deploy-backend.result }}" == "success" && "${{ needs.deploy-frontend.result }}" == "success" ]]; then
          echo "✅ Deployment successful"
          echo "Backend: Deployed to Render"
          echo "Frontend: Deployed to Netlify"
        else
          echo "❌ Deployment failed"
          echo "Backend status: ${{ needs.deploy-backend.result }}"
          echo "Frontend status: ${{ needs.deploy-frontend.result }}"
          exit 1
        fi