name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Generate API Documentation
  api-docs:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./apps/api
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate OpenAPI spec
      env:
        DATABASE_URL: sqlite:///./test.db
        SECRET_KEY: test-secret-key
      run: |
        python -c "
        import json
        import sys
        sys.path.append('.')
        from main import app
        
        # Generate OpenAPI JSON
        openapi_json = app.openapi()
        
        with open('openapi.json', 'w') as f:
            json.dump(openapi_json, f, indent=2)
        
        print('✅ OpenAPI spec generated')
        "
    
    - name: Upload API docs
      uses: actions/upload-artifact@v4
      with:
        name: api-documentation
        path: apps/api/openapi.json

  # Deploy Documentation (on main branch)
  deploy-docs:
    runs-on: ubuntu-latest
    needs: api-docs
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download API docs
      uses: actions/download-artifact@v4
      with:
        name: api-documentation
        path: ./docs/
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Generate documentation site
      run: |
        # Create a simple docs site
        mkdir -p docs-site
        
        cat > docs-site/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>LaVidaLuca API Documentation</title>
            <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3.25.0/swagger-ui.css" />
        </head>
        <body>
            <div id="swagger-ui"></div>
            <script src="https://unpkg.com/swagger-ui-dist@3.25.0/swagger-ui-bundle.js"></script>
            <script>
                SwaggerUIBundle({
                    url: './openapi.json',
                    dom_id: '#swagger-ui',
                    presets: [
                        SwaggerUIBundle.presets.apis,
                        SwaggerUIBundle.presets.standalone
                    ]
                });
            </script>
        </body>
        </html>
        EOF
        
        # Copy OpenAPI spec
        cp docs/openapi.json docs-site/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site
        destination_dir: api-docs